### ISSUE TITLE
Can't mount a volume 

### ISSUE THREAD

**Issue by pcasis** [hpe-storage/dory#54]
Hello 😃 ,

I'm using the hpe plugin to create dynamically volumes on a Nimble storage.

I followed this link https://developer.hpe.com/blog/doryd-a-dynamic-provisioner-for-docker-volume-plugins and ended with these configuration files :

```
---                             
kind: Pod                                               
apiVersion: v1                                          
metadata:                                               
  name: pod-test                                        
spec:                                                   
  containers:                                           
        - image: httpd:latest                           
          name: httpd                                   
          volumeMounts:                                 
            - name: httpd-persistent-storage            
              mountPath: /data                          
  volumes:                                              
        - name: httpd-persistent-storage                
          persistentVolumeClaim:                        
            claimName: pvc-test                         
---                                                     
apiVersion: v1                                          
kind: PersistentVolumeClaim                             
metadata:                                               
  name: pvc-test                                        
spec:                                                   
  accessModes:                                          
    - ReadWriteOnce                                     
  volumeMode: Filesystem                                
  resources:                                            
    requests:                                           
      storage: 1Gi                                      
  storageClassName: sc-test                             
---                                                     
kind: StorageClass                                      
apiVersion: storage.k8s.io/v1                           
metadata:                                               
 name: sc-test                                          
 annotations:                                           
  storageclass.kubernetes.io/is-default-class: "true"   
provisioner: dev.hpe.com/nimble                         
parameters:                                             
  description: "Volume provisioned sc-test StorageClass"
  folder: "data-test"                                 

```

The StorageClass and the PersistenceVolumeClaim are working as I can see the volume created in the folder data-test on the Nimble's side.

However I'm still having the error 32 when the volume is binded to the Pod/Container : 

> 

Normal | Scheduled | Successfully assigned default/pod-test to ste1ppoc3 | 14 minutes ago
-- | -- | -- | --
Warning | FailedMount | MountVolume.SetUp failed for volume  "sc-test-a5e937af-9c05-11e9-aa73-1c98ec2bb718" : mount command failed,  status: Failure, reason: rc=32 | a minute ago
Warning | FailedMount | Unable to mount volumes for pod  "pod-test_default(4cc17710-9c0f-11e9-b6c3-1c98ec2bb718)": timeout  expired waiting for volumes to attach or mount for pod  "default"/"pod-test". list of unmounted  volumes=[httpd-persistent-storage]. list of unattached  volumes=[httpd-persistent-storage default-token-jvh54] | a few seconds ago

Important thing to notice, when I execute the following command I get : 
```
sudo curl -XPOST --unix-socket /run/docker/plugins/nimble.sock http:/Plugin.Activate
{"implements":["VolumeDriver"],"Err":""}
```

Have you any idea on where this issue could came from ?

Regards 👍
